sudo: false
language: python
env:
    - TOXENV=py26
    - TOXENV=py27
install:
  - pip install -r test-requirements.txt --use-mirrors
script:
  - tox
addons:
  apt_packages:
      - pandoc
after_success:
  coveralls
